### ISSUE TITLE
just two suggestions

### ISSUE THREAD

**Issue by zachcheung** [noureddin/gdrive-dl#1]
Just two suggestions.
1. use `#!/usr/bin/env perl` instead of `#!/usr/local/bin/perl`, and `#!/usr/bin/env bash` instead of `#!/bin/bash`
2. When download folder link, download files in the folder_name directory, not directly in the current directory, then it would be better to download multiple folder links in scripts(sometimes filename in different folder links would be same, while each folder_name are different.)

**Comment by noureddin** [comment]
Thanks for your suggestions :+1: 

About the second suggestion, this is a great idea. In the very recent version, a switch, to download to folder_name, is now included.

About the first suggestion, IMHO, this may be important for python and maybe perl also, but '#!/bin/bash' very rarely causes a problem, among the GNU\Linuxes at least. Any way, we thinking about changing to pyhton or perl to make it as portable as possible. So, this might not be an issue :) .

**Comment by zachcheung** [comment]
yep, for '#!/bin/bash' it's almost OK in GNU/Linux, when issue 'type bash' under Arch, it'll show 'bash is /usr/bin/bash' while '/bin/bash' still exists, but Bash installed via ports under FreeBSD would be '/usr/local/bin/bash'. :)

**Comment by noureddin** [comment]
Well, You have persuaded me :)
However, using /bin/sh may be more portable than bash. So, a new entry is added to to the todo-list.
