### ISSUE TITLE
failed to download Google Docs editor format file

### ISSUE THREAD

**Issue by zachcheung** [noureddin/gdrive-dl#2]
```
17:50 /tmp/gdrive-dl
$ls
17:50 /tmp/gdrive-dl
$/opt/gdrive-dl/gdrive-dl 'https://drive.google.com/folderview?id=0B7r4qfdPc2V1V1IzcUtXR2JxcDA&usp=sharing'
Getting a
Getting a.txt
Getting b
Getting b.txt
Now in folder/
Getting a.txt
Getting b.txt
mkdir: cannot create directory `a': File exists
/opt/gdrive-dl/gdrive-dl: line 310: cd: a: Not a directory
Now in a/
Now in b/
17:51 /tmp/gdrive-dl
$ls -hl
total 12K
-rw-r--r-- 1 zach zach    0 Jan  6 17:50 a
-rw-r--r-- 1 zach zach   29 Jan  6 17:50 a.txt
-rw-r--r-- 1 zach zach    0 Jan  6 17:50 b
-rw-r--r-- 1 zach zach   29 Jan  6 17:51 b.txt
drwxr-xr-x 2 zach zach 4.0K Jan  6 17:51 folder/
```

**Comment by noureddin** [comment]
Currently, Google Docs is not supported. We are trying to support it as soon as possible.
The problem with Google Docs is: if you want to download a regular file, just the ID is what you need; but if you want to download a Google document, you need the ID and the format, which may vary depending on the file type, and your choise; e.g., a document can be downloaded as .docx, .odf, .pdf, .html, or even .txt.
Supporting Google Docs is added to our Todo list, in the wiki :) .

**Comment by zachcheung** [comment]
Sorry, didn't see Wiki before filing the issue. :P

**Comment by noureddin** [comment]
BTW, supporting Google Docs is added to the todo-list after you've opened this issue :D
